export const mockdataDanhSachNV = [
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    reason: "Không nghỉ",
    tName: "Chưa cập nhật",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    reason: "Không nghỉ",
    tName: "Chưa cập nhật",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    reason: "Không nghỉ",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    reason: "Không nghỉ",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    reason: "Không nghỉ",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    reason: "Không nghỉ",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    reason: "Không nghỉ",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },

  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    reason: "Không nghỉ",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  },
  {
    id: "146111",
    name: "Phạm Nguyễn Xuân Khôi",
    companyName: "Công ty cổ phần Thanh toán Hưng Hà 2",
    apartmentName: "Kỹ thuật",
    tName: "Chưa cập nhật",
    groupName: "Chưa cập nhật",
    job: "Nhân viên chính thức",
    gender: "Nam",
    reason: "Không nghỉ",
    dob: "04/02/1998",
    state: "Đã lập gia đình",
    info: "Email:fafaaafafafaafa@gmail.com",
    startDate: "16/02/2023",
    degree: "Đại Học",
    exp: "Chưa cập nhật"
  }
]
